# Module 1 — NumPy Essentials (Numerical Computing)

This notebook covers core NumPy concepts useful for numerical computing and as a foundation for scientific Python.

Lessons: 1.1 Introduction, 1.2 Creating arrays, 1.3 Attributes & Indexing, 1.4 Operations & Aggregations, 1.5 Random & Linear Algebra

Run cells top→bottom. Each lesson includes explanation, code demo, and interpretation notes.

## Lesson 1.1 — Why NumPy?

**Key points:**
- NumPy = Numerical Python: efficient arrays, vectorized math, foundation for Pandas/Scipy/ML frameworks.
- Python lists are general-purpose but slow for numeric operations; NumPy arrays are homogeneous and memory-efficient.
- Think in arrays, not loops.


In [1]:
import numpy as np
import time
# pip install numpy
python_list = list(range(1_000_000))
numpy_array = np.arange(1_000_000)

start = time.time()
s1 = sum(python_list)
t1 = time.time()-start
start = time.time()
s2 = numpy_array.sum()
t2 = time.time()-start
print('Python sum time: {:.4f}s, NumPy sum time: {:.4f}s'.format(t1, t2))
print('Equal sums?', s1==s2)

Python sum time: 0.0094s, NumPy sum time: 0.0009s
Equal sums? True


**Interpretation:**
- NumPy operations are generally much faster for large arrays because they are implemented in optimized C loops.
- Use NumPy when performing numerical computations repeatedly or over large data.

## Lesson 1.2 — Creating Arrays

Ways to create arrays: `np.array`, `np.arange`, `np.linspace`, special arrays like `zeros`, `ones`, `eye`.

In [2]:
a = np.array([1,2,3])
r = np.arange(0,10,2)
l = np.linspace(0,1,5)
z = np.zeros((2,3))
o = np.ones((3,3))
I = np.eye(4)
a, r, l, z, o, I

(array([1, 2, 3]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

**Notes:**
- `arange` is like Python `range` but returns an array; `linspace` is great for plotting evenly spaced values.
- `zeros/ones/eye` useful for initialization.

## Lesson 1.3 — Attributes & Indexing

Understand `.shape`, `.size`, `.ndim`, `.dtype` and indexing/slicing including boolean masks.

In [3]:
arr = np.arange(12).reshape(3,4)
print('arr:\n', arr)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)
print('arr[1,2]=', arr[1,2])
print('arr[:,1]=', arr[:,1])
print('even mask:', arr[arr % 2 == 0])

arr:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)
size: 12
ndim: 2
dtype: int64
arr[1,2]= 6
arr[:,1]= [1 5 9]
even mask: [ 0  2  4  6  8 10]


**Tips:**
- Use boolean masks to filter arrays quickly without loops.
- Slicing returns views when possible (be mindful of copies vs views).

## Lesson 1.4 — Array Operations & Aggregations

Vectorized ops, broadcasting, aggregations (`sum, mean, std, median, percentile`) and ufuncs.

In [5]:
arr = np.array([10,20,30,40])
print('arr + 5 ->', arr + 5)
print('arr * 2 ->', arr * 2)
M = np.ones((3,4)) + arr  # broadcasting arr across rows
print('broadcast shape:', M.shape)
print('sum, mean, median, 90th percentile:', arr.sum(), arr.mean(), np.median(arr), np.percentile(arr,90))
print('ufuncs sqrt/log:', np.sqrt(arr), np.log(arr))
M

arr + 5 -> [15 25 35 45]
arr * 2 -> [20 40 60 80]
broadcast shape: (3, 4)
sum, mean, median, 90th percentile: 100 25.0 25.0 37.0
ufuncs sqrt/log: [3.16227766 4.47213595 5.47722558 6.32455532] [2.30258509 2.99573227 3.40119738 3.68887945]


array([[11., 21., 31., 41.],
       [11., 21., 31., 41.],
       [11., 21., 31., 41.]])

**Interpretation:**
- Broadcasting lets you combine arrays of different shapes when compatible.
- Aggregation functions are highly optimized — use them instead of Python loops.

## Lesson 1.5 — Random Numbers & Linear Algebra

Random generators and basic linear algebra (`dot`, `inv`, `eig`). Useful for simulations and ML.

In [6]:
np.random.seed(0)
print('rand:', np.random.rand(5))
print('randn:', np.random.randn(5))
print('randint:', np.random.randint(1,10,5))
print('choice:', np.random.choice([1,2,3,4], size=5))
rolls = np.random.randint(1,7,10000)
print('Empirical P(roll==6):', np.mean(rolls==6))
A = np.array([[1,2],[3,4]])
print('A @ A:\n', A @ A)
print('inv(A):\n', np.linalg.inv(A))
vals, vecs = np.linalg.eig(A)
print('eigvals:', vals)

rand: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
randn: [-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]
randint: [6 9 5 4 1]
choice: [4 2 3 4 4]
Empirical P(roll==6): 0.1666
A @ A:
 [[ 7 10]
 [15 22]]
inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]
eigvals: [-0.37228132  5.37228132]
